<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros2_fra2mo)/urdf/utility_macro.xacro" />

  <!-- WHOLE BASE MACRO-->
  <xacro:macro name="fra2mo_base" > <!--fb : front, back ; lr: left, right -->

    <!-- Base properties -->
    <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="5" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.13" /> 
   
    <!-- Actual body/chassis of the robot -->
    <link name="base_footprint">
    </link>

    <link name="base_link">
      <!-- Inertial properties -->
      <inertial>
        <origin xyz="0 0 -0.1" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <!-- Visual representation -->
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <!-- Collision properties -->
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.05}" rpy="0 0 0" />
      </collision> 
      <collision>
        <geometry>
          <sphere radius="0.019" />
        </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>       
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

        <!-- Additional Links -->
    <link name="lidar_link" />
        <!-- RGB Camera (D435) -->
    <link name="d435_link">
      <visual>
          <geometry>
              <box size="0.005 0.005 0.005"/>
          </geometry>
      </visual>
    </link>

    <!-- Joints -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.019" rpy="0 0 0" />
    </joint>
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="d435_joint" type="fixed">
      <parent link="base_link" />
      <child link="d435_link" />
      <origin xyz="0.110925 0.0 0.06670" rpy="0 0.5 0" />
    </joint>
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="0.0 0.0 -0.025" rpy="0 0 0" />
    </joint>

    <!-- Gazebo Material Assignments 
    <gazebo reference="base_link">
      <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>-->

    <!-- Transmissions -->

    <transmission name="left_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint" />
      <actuator name="left_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <transmission name="right_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint" />
      <actuator name="right_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    


    <gazebo>
      <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
        <ros>
          <namespace>fra2mo</namespace>
        </ros>
        <parameters>$(find ros2_fra2mo)/config/fra2mo_controllers.yaml</parameters>
        <controller_manager_name>controller_manager</controller_manager_name>
      </plugin>
    </gazebo>



    <!-- Plugin for differential drive control in Gazebo--> 
    <gazebo>
      <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <!--<frame_id>base_footprint</frame_id> TO LOOK
        <ignition_frame_id>base_footprint</ignition_frame_id>--> 
        <odom_publish_frequency>50</odom_publish_frequency>
        <topic>cmd_vel</topic>
      </plugin>
    </gazebo>



      <gazebo reference="d435_link">
        <!-- RGB Camera -->
        <sensor type="camera" name="d435_rgb_camera">
          <camera>
            <horizontal_fov>1.57</horizontal_fov>
            <vertical_fov>1.57</vertical_fov>
            <image>
              <width>640</width>
              <height>360</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.01</near>
              <far>2</far>
            </clip>
          </camera>
          <always_on>1</always_on>
          <update_rate>30</update_rate>
          <visualize>true</visualize>
          <frame_id>laser_frame</frame_id>
          <topic>image_raw</topic>
          <topic>camera_info</topic>
        </sensor>
      </gazebo>


  </xacro:macro>
</robot>

